name: Terraform Test
    
on: 
  push

jobs:
  terrafrom-test:
    name: Terraform Test Job
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v2

    # Install the latest version of the Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    # Initialize a new or existing Terraform working directory
    - name: Initialize Terraform
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Initialize Terraform
      run: terraform fmt -check -recursive
    
    # Validate Terraform files
    - name: Terraform Validate
      run: terraform validate