name: Terraform Plan Apply
    
on: 
  push

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terrafrom-plan:
    name: Terraform Plan Job
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v2

    # Login to Azure via Azure CLI
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Install the latest version of the Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    # Initialize a new or existing Terraform working directory
    - name: Initialize Terraform
      run: terraform init
      
    # Initialize a new or existing Terraform working directory
    - name: Generate an execution plan for Terraform
      run: terraform plan -out=tfplan.out

    # Save plan to artifacts
    - name: Generate an execution plan for Terraform
      run: terraform plan -out=tfplan.out

    - name: Archive Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan.out